# Generated by Django 4.1.2 on 2024-06-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_screen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='screen_image/'),
        ),
        migrations.AddField(
            model_name='screen',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
