# Generated by Django 4.1.2 on 2024-06-05 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_screen', '0002_screen_image_screen_name_section_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='screen',
            name='quality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='screen',
            name='sound',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='rows',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='screen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='theatre_screen.screen'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='screens/'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='layout',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='screen',
        ),
    ]
