# Generated by Django 4.1.2 on 2024-06-09 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theatre_screen', '0003_alter_seat_unique_together_screen_quality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='theatre',
            field=models.ForeignKey(default=71, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
