# Generated by Django 4.1.2 on 2024-06-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_screen', '0005_alter_screen_theatre'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='selected_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
