# Generated by Django 5.0.6 on 2024-06-11 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_screen', '0006_seat_is_selected_seat_selected_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='selected_time',
            new_name='selected_at',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='is_selected',
        ),
        migrations.AddField(
            model_name='seat',
            name='selected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_seats', to=settings.AUTH_USER_MODEL),
        ),
    ]
