# Generated by Django 5.0.6 on 2024-06-18 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_screen', '0008_seat_reserved_by'),
        ('theatre_side', '0016_alter_shows_theatre'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='theatre_side.shows'),
        ),
    ]
