# Generated by Django 5.0.6 on 2024-06-18 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_screen', '0010_remove_seat_show_showseatreservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='is_reserved',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='reserved_by',
        ),
        migrations.RemoveField(
            model_name='showseatreservation',
            name='selected_at',
        ),
        migrations.RemoveField(
            model_name='showseatreservation',
            name='selected_by',
        ),
    ]
