# Generated by Django 5.0.6 on 2024-06-18 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_screen', '0011_remove_seat_is_reserved_remove_seat_reserved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='selected_at',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='selected_by',
        ),
        migrations.AddField(
            model_name='showseatreservation',
            name='selected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='showseatreservation',
            name='selected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='show_selected_seats', to=settings.AUTH_USER_MODEL),
        ),
    ]
