# Generated by Django 4.1.2 on 2024-05-28 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_user_auth_provider_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth_data')),
                ('gender', models.CharField(blank=True, max_length=20, null=True, verbose_name='gender')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('pincode', models.CharField(blank=True, max_length=10, null=True, verbose_name='pincode')),
                ('city', models.CharField(blank=True, max_length=250, null=True, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='state')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
