# Generated by Django 4.1.2 on 2024-06-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_remove_user_user_image_userprofile_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('normal', 'Normal User'), ('theatre', 'Theatre')], default='normal', max_length=10),
        ),
    ]
