# Generated by Django 5.0.6 on 2024-07-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_mobile_verified',
            field=models.BooleanField(default=False),
        ),
    ]
