# Generated by Django 4.1.2 on 2024-04-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('theater_name', models.CharField(blank=True, max_length=255, null=True)),
                ('theater_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('theater_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('google_map_link', models.URLField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('town', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
