# Generated by Django 4.1.2 on 2024-04-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_side', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='password',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
