# Generated by Django 4.1.2 on 2024-05-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_side', '0005_theatre_admin_allow'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='liecense',
            field=models.ImageField(blank=True, null=True, upload_to='liecense/'),
        ),
    ]
