# Generated by Django 4.1.2 on 2024-05-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_side', '0007_shows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shows',
            name='end_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shows',
            name='start_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
