# Generated by Django 4.1.2 on 2024-06-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_side', '0009_alter_theatre_options_remove_theatre_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatre',
            name='liecense',
        ),
        migrations.AddField(
            model_name='theatre',
            name='license',
            field=models.ImageField(blank=True, null=True, upload_to='license/'),
        ),
    ]
