# Generated by Django 4.1.2 on 2024-06-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_side', '0010_remove_theatre_liecense_theatre_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatre',
            name='password',
        ),
    ]
