# Generated by Django 4.1.2 on 2024-06-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_side', '0011_remove_theatre_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shows',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shows',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
