# Generated by Django 4.1.2 on 2024-06-09 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_screen', '0003_alter_seat_unique_together_screen_quality_and_more'),
        ('theatre_side', '0012_alter_shows_date_alter_shows_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='theatre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theatre_side.theatre'),
        ),
        migrations.AlterField(
            model_name='shows',
            name='screen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theatre_screen.screen'),
        ),
    ]
