# Generated by Django 5.0.6 on 2024-06-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_bookings_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='seat_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
