# Generated by Django 5.0.6 on 2024-06-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookings_seat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='seat_number',
            field=models.JSONField(default=list),
        ),
    ]
