# Generated by Django 5.0.6 on 2024-07-08 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_bookings_seat_number'),
        ('theatre_side', '0016_alter_shows_theatre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='theatre_side.shows'),
        ),
    ]
