# Generated by Django 5.0.6 on 2024-07-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_offlinebookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinebookings',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
