# Generated by Django 5.0.6 on 2024-08-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_offlinebookings_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='ticket_expiration',
            field=models.BooleanField(default=False),
        ),
    ]
